# action.yml
name: 'ok-validate'
description: 'Use an Open Knowledge Framework schema to validate your manifest'
inputs:
  cpu-num:
    description: 'How many cores to use'
    required: false
    default: '4'
  ok:
    description: 'Which preset Open Knowledge Framework schema to use for validation. Should be one of ("okh")'
    required: false
    default: 'okh'
  parser:
    description: 'YAML library to load file'
    required: false
    default: 'pyyaml'
  path:
    description: 'The path to your mainfest or manifests relative to your workspace'
    required: true
    default: './'
  schema:
    description: 'The full path to an Open Knowledge Framework schema or custom schema to use for validation'
    required: false
    default: ''
  strict:
    description: 'Should the schema validator be run in strict mode?'
    required: false
    default: 'false'
outputs:
  results:
    description: 'The results of the validator'
runs:
  using: 'docker'
  image: 'Dockerfile'